permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

# 作者信息
author: 
  name: 海天心Y2kking
  email: 182036669@qq.com
  link: http://cometrue.top
  weibo: http://weibo.com/1419491963
  github: http://github.com/yusmile

# 站点信息
title: cometrue.top
description: The Pursuit of Happyness
url: http://cometrue.top
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://7u2ho6.com1.z0.glb.clouddn.com/site-avatar.png
favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

# google analytics 设置
ga:
  id: UA-54767140-1
  url: cometrue.top

# disqus 设置
disqus:
  shortname: butler
